name: ci
on:
  push:
    branches:
      - master

jobs:
  lint:
    name: code linting
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: install dependencies
        run: pip install -r requirements-dev.txt
      - name: run ruff linter
        run: ruff check .
  test:
    name: unit testing
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: run pytest
        run: pytest .
    

