name: ci
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: install dependencies
        run: pip install -r requirements-dev.txt
      - name: build package
        run: python -m build
